title: 我的主页
author: admin
description: 个人技术博客
lang: zh-CN

remote_theme: cotes2020/jekyll-theme-chirpy

# 确保下面这两行没有写错，且冒号后面有空格
url: "https://你的用户名.github.io"
baseurl: ""

# Chirpy 主题需要的必备插件
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
